# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Claire' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FSCalendar
  pod 'FSCalendar'

  # Pods for Realm (Havent tried this yet)
  pod 'RealmSwift', '~> 2.0.2'

  # Pod for Folding Cell
  # pod 'FoldingCell' '~> 2.0.3'

  # Pods for Charts
  pod 'Charts'
  
  # Pods for Color
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  # Pod for FontAwesome
  pod 'FontAwesome.swift'

  # Pod for Eureka
  pod 'Eureka', '~> 2.0.0-beta.1'
  
  # Pods for Banners
  pod 'BRYXBanner'
  
  # Pods for Empty Table Views
  pod 'DZNEmptyDataSet'

  # Pods for Tab Bar Animation
  pod 'RAMAnimatedTabBarController', "~> 2.0.13"

  target 'ClaireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClaireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end

end
